---
apiVersion: v1
kind: Pod
metadata:
  name: base-app
  labels:
    app: base-app
spec:
  containers:
    - name: front-end
      image: klavenx/image-tests/base:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: base-app-service
spec:
  selector:
    app: base-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080