---
apiVersion: v1
kind: Pod
metadata:
  name: scratch-app
  labels:
    app: scratch-app
spec:
  containers:
    - name: front-end
      image: nullchannel/container-tests-scratch:latest
      ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: scratch-app-service
spec:
  type: NodePort
  selector:
    app: scratch-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090