name: publish_images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine.dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            nullchannel/container-tests/alpine:latest
      -
        name: Build and push base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base.dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            nullchannel/container-tests/base:latest
      -
        name: Build and push deb
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deb.dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            nullchannel/container-tests/deb:latest
      -
        name: Build and push scratch
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./scratch.dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            nullchannel/container-tests/scratch:latest